# Generated by Django 4.0.4 on 2022-05-13 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date']},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date_commande',
            new_name='order_date',
        ),
    ]
